---

# This project is a mix of languages; default to bash for now
language: bash

install:
  # Install yamllint for testing YAML files (including Ansible)
  - pip install --user yamllint
  # Install ansible-lint for testing Ansible scripts
  - pip install --user ansible-lint

script:
  # Validate our Ansible playbooks
  - python -myamllint -f parsable playbook.yml
  # ANSIBLE0012 seems like it's usually good practice, but doesn't really suit our use case here - if we tell it to publish, we want it to publish
  - ansible-lint -p playbook.yml -x ANSIBLE0012
  # TODO Add additional validation/build steps here

notifications:
  email: false

