version: '2.1'
volumes:
  rabbitmq_data:
  mysql_data:
  datavault_active_data:
  datavault_archive_data:
  datavault_temp_data:
  datavault_meta_data:
  datavault_user_data:
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
    environment:
      RABBITMQ_DEFAULT_USER: datavault
      RABBITMQ_DEFAULT_PASS: datavault
    networks:
      - mqnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      # At the moment, the database is deleted when the broker stops, but that is due to be corrected
      - mysql_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: unbr34kable
      MYSQL_DATABASE: datavault
      MYSQL_USER: datavault
      MYSQL_PASSWORD: datavault
    networks:
      - dbnet

  workers:
    build:
      context: ../src/datavault/
      dockerfile: worker.Dockerfile
    volumes:
      # Cannot use a single volume for /tmp/datavault, as the subdirs must already exist before use - the code will not create them
      - datavault_active_data:/tmp/datavault/active:rw
      - datavault_archive_data:/tmp/datavault/archive:rw
      - datavault_temp_data:/tmp/datavault/temp:rw
      - datavault_meta_data:/tmp/datavault/meta:rw
      - datavault_user_data:/Users:rw
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq

  broker:
    build:
      context: ../src/datavault/
      dockerfile: broker.Dockerfile
    volumes:
      - datavault_active_data:/tmp/datavault/active:rw
      - datavault_archive_data:/tmp/datavault/archive:rw
      - datavault_temp_data:/tmp/datavault/temp:rw
      - datavault_meta_data:/tmp/datavault/meta:rw
      - datavault_user_data:/Users:rw
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

  web:
    build:
      context: ../src/datavault/
      dockerfile: webapp.Dockerfile
    volumes:
      - datavault_active_data:/tmp/datavault/active:rw
      - datavault_archive_data:/tmp/datavault/archive:rw
      - datavault_temp_data:/tmp/datavault/temp:rw
      - datavault_meta_data:/tmp/datavault/meta:rw
      - datavault_user_data:/Users:rw
    ports:
      - "80:8080"
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

networks:
  dbnet:
    driver: bridge
  mqnet:
    driver: bridge
