version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./docker/rabbitmq_data:/bitnami
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: datavault
      RABBITMQ_DEFAULT_PASS: datavault
    networks:
      - mqnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:5.7
    ports:
      - "53306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unbr34kable
      MYSQL_DATABASE: datavault
      MYSQL_USER: datavault
      MYSQL_PASSWORD: datavault
    networks:
      - dbnet

  workers:
    build:
      context: ../src/datavault/datavault-worker
    volumes:
      - ./docker/tmp/datavault/active:/tmp/datavault/active:rw
      - ./docker/tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./docker/tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./docker/tmp/datavault/meta:/tmp/datavault/meta:rw
      - ./docker/tmp/Users:/Users:rw
      - ./docker/config:/docker_datavault-home/config/
      - ./docker/scripts:/docker_datavault-home/scripts/
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq

  web:
    build:
      context: ../src/datavault/datavault-webapp
    ports:
      - "58080:8080"
    volumes:
      - ./docker/tmp/datavault/active:/tmp/datavault/active:rw
      - ./docker/tmp/datavault/archive:/tmp/datavault/archive:rw
      - ./docker/tmp/datavault/temp:/tmp/datavault/temp:rw
      - ./docker/tmp/datavault/meta:/tmp/datavault/meta:rw
      - ./docker/tmp/Users:/Users:rw
      - ./docker/config:/docker_datavault-home/config/
      - ./docker/scripts:/docker_datavault-home/scripts/
      - ./datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/lib:/docker_datavault-home/lib
      - ./datavault-assembly/target/datavault-assembly-1.0-SNAPSHOT-assembly/datavault-home/webapps:/docker_datavault-home/webapps
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

networks:
  dbnet:
    driver: bridge
  mqnet:
    driver: bridge
