version: '2.1'

volumes:
  rabbitmq_data:
  mysql_data:
  datavault_archive_data:
  datavault_user_data:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw
    environment:
      RABBITMQ_DEFAULT_USER: datavault
      RABBITMQ_DEFAULT_PASS: efgh5678
    networks:
      - mqnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      # At the moment, the database is deleted when the broker stops, but that is due to be corrected
      - mysql_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: unbr34kable
      MYSQL_DATABASE: datavault
      MYSQL_USER: datavault
      MYSQL_PASSWORD: abcd1234
    networks:
      - dbnet
    healthcheck:
      test: mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -D$$MYSQL_DATABASE -e "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 5

  workers:
    image: ${REGISTRY}/rdss-datavault/worker
    volumes:
      - datavault_user_data:/Users:rw
      # This volume has to be shared with the worker task, in order for the broker to access the metadata after the worker has updated it
      # That's a bug - the worker should instead send the metadata back via rabbitmq - once it's fixed the volume can be removed/unshared
      - datavault_archive_data:/tmp/datavault:rw
    environment:
      MYSQL_PASSWORD: abcd1234
      RABBITMQ_PASSWORD: efgh5678
      AWS_S3_BUCKET: rdss-datavault-archive
    networks:
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

  broker:
    image: ${REGISTRY}/rdss-datavault/broker
    environment:
      MYSQL_PASSWORD: abcd1234
      RABBITMQ_PASSWORD: efgh5678
      AWS_S3_BUCKET: rdss-datavault-archive
    env_file: secrets.env
    volumes:
      - datavault_user_data:/Users:rw
      # This volume has to be shared with the worker task, in order for the broker to access the metadata after the worker has updated it
      # That's a bug - the worker should instead send the metadata back via rabbitmq - once it's fixed the volume can be removed/unshared
      - datavault_archive_data:/tmp/datavault:rw
    networks:
      - default
      - dbnet
      - mqnet
    depends_on:
      - rabbitmq
      - mysql

  web:
    image: ${REGISTRY}/rdss-datavault/web
    ports:
      - "80:8080"

networks:
  dbnet:
    driver: bridge
  mqnet:
    driver: bridge
